[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18.0.0"
  NPM_FLAGS = "--prefix=frontend"
  NODE_OPTIONS = "--max_old_space_size=4096"
  CI = "false"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Dev server configuration
[dev]
  command = "npm start --prefix frontend"
  port = 3000
  targetPort = 3000
  publish = "frontend/build"

# Build plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Caching configuration
[[plugins]]
  package = "netlify-plugin-cache"
  
  [plugins.inputs]
  paths = [
    "frontend/node_modules",
    ".netlify/cache"
  ]

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
